### ISSUE TITLE
Fatal Exception: android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by angelolloqui** [InflationX/ViewPump#64] opened 2021-05-11 17:29 UTC
We have this crash repeated hundreds of times each month. It is basically our major crash reason in the app. I have seen that the issue is coming during inflation, and seems related to view pump. Is it because of newer versions of appCompat? any planned fix for it?
According to my crash analytics data, it happens in all kind of devices and OS versions, I can not find a pattern there.

Using io.github.inflationx:viewpump:2.0.3 

```
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x0
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
       at android.content.res.Resources.loadXmlResourceParser(Resources.java:2400)
       at android.content.res.Resources.getLayout(Resources.java:1252)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:530)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
       at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:425)
       at android.widget.ArrayAdapter.getView(ArrayAdapter.java:416)
       at x90.getView(chromium-TrichromeWebViewGoogle.aab-stable-443009133:2)
       at android.widget.AbsListView.obtainView(AbsListView.java:2412)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
       at android.widget.ListView.onMeasure(ListView.java:1323)
       at android.view.View.measure(View.java:25470)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25470)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25470)
       at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:146)
       at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:71)
       at android.view.View.measure(View.java:25470)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25470)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:25470)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
       at android.view.View.measure(View.java:25470)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3399)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2203)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2488)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1954)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8180)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
       at android.view.Choreographer.doCallbacks(Choreographer.java:878)
       at android.view.Choreographer.doFrame(Choreographer.java:811)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7698)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by ZacSweers** [comment] 2023-03-25 02:15
Closing as a dupe of #60 I think

**Closed by ZacSweers** 2023-03-25 02:15 UTC
