### ISSUE TITLE
Remove the `-` prefix for internal files because they don't work?

### ISSUE THREAD

**Issue by drakeet** [InflationX/ViewPump#39] opened 2019-04-04 07:07 UTC
Hi, I saw #24 mentioned: 

> The `-` prefixes on internal classes are to hide them from java, as they're otherwise visible as public classes

But in fact, this did not really achieve the effect we expected:

![image](https://user-images.githubusercontent.com/5214214/55535970-2fc12080-56eb-11e9-87ed-533101fcb353.png)

And we have moved them to an internal package, so are we going to remove these prefixes?

**Comment by ZacSweers** [comment] 2019-04-04 07:37
you're right! But the problem is that the classes in those files are missing. Will PR a fix

**Comment by drakeet** [comment] 2019-04-04 07:55
Nice! Actually, we can see these classes in Java and use them without compile errors (although the IDE will warn us).

So I prefer removing them. Kotlin design is this, we have used the internal scope and the internal package, and the rest is handed over to the Kotlin tools. Removing the prefixes will make us more convenient in the future. 😋

**Comment by ZacSweers** [comment] 2019-04-04 07:59
Kotlin tools can't be relied on for Java consumers though, which is the point of doing this. Fixed in #40

**Closed** 2019-04-04 08:05 UTC
