### ISSUE TITLE
ANR from ViewPump.init(ViewPump.builder()

### ISSUE THREAD

**Issue by TobiasReich** [InflationX/ViewPump#53] opened 2019-11-01 14:05 UTC
My app gets sometimes an ANR from that line
`ViewPump.init(ViewPump.builder()`

looking like this:

> "main" prio=5 tid=1 Runnable
>   | group="main" sCount=0 dsCount=0 flags=0 obj=0x72b266f0 self=0x7c85cc3a00
>   | sysTid=25641 nice=0 cgrp=default sched=0/0 handle=0x7c8a49c9b0
>   | state=R schedstat=( 1753354711 262386751 2208 ) utm=30 stm=145 core=0 HZ=100
>   | stack=0x7ff109e000-0x7ff10a0000 stackSize=8MB
>   | held mutexes= "mutator lock"(shared held)

Not sure it's actually the framworks fault but maybe anyone knows what this means

**Comment by drakeet** [comment] 2019-12-09 09:55
I also encountered this problem, and the solution was to downgrade to version 1.0, that is, without Kotlin version, it was resolved. @jbarr21 @ZacSweers

**Comment by drakeet** [comment] 2019-12-09 09:58
I'm pretty sure this was a problem with version 2.0, and it took me a long time to track this ANR, and it took me to finally find a solution through git commit rollback. Now finally someone has met, I believe it is not just on me!

**Comment by ZacSweers** [comment] 2019-12-09 16:39
That's not really actionable for us. Can you provide a reproducing sample?


________________________________

**Comment by drakeet** [comment] 2019-12-09 23:59
Sorry, it is hard, because It only happened on my user's device, I contacted him remotely to verify it, but I never found the root cause. Hope someone will help...

**Comment by Rufim** [comment] 2020-01-07 10:03
I get same bug on one of my devices

  java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/os/BuildCompat;
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.<init>(-ViewPumpLayoutInflater.kt:25)
        at io.github.inflationx.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:25)
        at io.github.inflationx.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:22)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at io.github.inflationx.viewpump.ViewPumpContextWrapper.getInflater(ViewPumpContextWrapper.kt)
        at io.github.inflationx.viewpump.ViewPumpContextWrapper.getSystemService(ViewPumpContextWrapper.kt:31)
        at android.view.LayoutInflater.from(LayoutInflater.java:232)
        at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:167)
        at android.app.Activity.getSystemService(Activity.java:5593)
        at android.view.LayoutInflater.from(LayoutInflater.java:232)
        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:305)
        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:316)
        at android.app.Activity.attach(Activity.java:6606)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2600)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6146)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.os.BuildCompat" on path: DexPathList[[zip file "/data/app/ru.samlib.client-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.samlib.client-1/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.<init>(-ViewPumpLayoutInflater.kt:25) 
        at io.github.inflationx.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:25) 
        at io.github.inflationx.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:22) 
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) 
        at io.github.inflationx.viewpump.ViewPumpContextWrapper.getInflater(ViewPumpContextWrapper.kt) 
        at io.github.inflationx.viewpump.ViewPumpContextWrapper.getSystemService(ViewPumpContextWrapper.kt:31) 
        at android.view.LayoutInflater.from(LayoutInflater.java:232) 
        at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:167) 
        at android.app.Activity.getSystemService(Activity.java:5593) 
        at android.view.LayoutInflater.from(LayoutInflater.java:232) 
        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:305) 
        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:316) 
        at android.app.Activity.attach(Activity.java:6606) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2600) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6146) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ZacSweers** [comment] 2020-01-07 15:44
@rufim that looks unrelated and like a problem with your build missing classes in the final decision files.

**Comment by juancoob** [comment] 2020-06-01 15:19
Hello, I would like to let you know in older projects without AndroidX, some devices (honor x9 and redmi note in my case) won't work using the last ViewPump library due to ANR problems. So I needed to downgrade to the version 1.0 to make them work. Thanks for your effort in that library 😃

**Comment by dirol90** [comment] 2020-08-08 20:37
Same problem is  I use version 1.0  work older devices like honor or Xiaomi, but in this case, I have a problem with all-new phones with android 10
`android.view.InflateException: Binary XML file line #17 in.com.engage./abc_screen_simple: Binary XML file line #17 in.com.engage./abc_screen_simple: Error inflating class android.support.v7.widget.FitWindowsLinearLayout`

**Comment by Dhatchanamoorthy** [comment] 2020-11-06 12:57
@dirol90  did u fix this issue? after updating library for android10 crash now im getting crash on lower device below 6.

**Comment by ZacSweers** [comment] 2023-03-25 02:16
Closing due to lack of information

**Closed by ZacSweers** 2023-03-25 02:16 UTC
