### ISSUE TITLE
Crash while inflating

### ISSUE THREAD

**Issue by dduvedi** [InflationX/ViewPump#59] opened 2020-10-16 07:33 UTC
Fatal Exception: android.view.InflateException: Binary XML file line #14: Error inflating class android.widget.TextView
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$NameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.java:290)
       at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.java:14)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:18)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.java:36)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.java:169)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.superOnCreateView(-ViewPumpLayoutInflater.java:233)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$superOnCreateView(-ViewPumpLayoutInflater.java:19)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$ParentAndNameAndAttrsViewCreator.onCreateView(-ViewPumpLayoutInflater.java:271)
       at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.java:14)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:18)
       at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.java:30)
       at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.java:36)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.onCreateView(-ViewPumpLayoutInflater.java:151)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:57)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.java:48)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at com.payu.payumoney.activities.CreateWebsiteActivity.showBackButtonDialogIfNecessary(CreateWebsiteActivity.java:111)
       at com.payu.payumoney.activities.CreateWebsiteActivity.access$000(CreateWebsiteActivity.java:43)
       at com.payu.payumoney.activities.CreateWebsiteActivity$1.onClick(CreateWebsiteActivity.java:80)
       at android.view.View.performClick(View.java:4848)
       at android.view.View$PerformClick.run(View.java:20300)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5839)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by Allan-Nava** [comment] 2021-04-02 15:00
Same problem when I try to use navHostFragment

**Comment by linhnv106** [comment] 2022-06-07 15:56
@chrisjenx  any update on this issue ? seem like lot of people facing this

**Comment by chrisjenx** [comment] 2022-06-07 16:05
Theres not enough here to determine what the issue is, try inflating the view without ViewPump to see if it goes away as the stack trace suggests something else.
Otherwise we'll need an example to replicate.

Thanks

**Comment by linhnv106** [comment] 2022-06-08 04:43
okay, for anyone has same issue with using navHostFragment, here is my solution : 

- remove navGraph from xml
- inflate and set Graph in your activity onCreate  method : 
`        val navGraph = navController.navInflater.inflate(R.navigation.settings)
        navController.graph = navGraph`

**Comment by ZacSweers** [comment] 2023-03-25 02:11
Closing due to lack of information, revisit if you have a minimally reproducing sample

**Closed by ZacSweers** 2023-03-25 02:11 UTC
